food/urls.py
from django.urls import path
from . import views

# Use namespacing to avoid apps names conflict
app_name = 'food'

urlpatterns = [
    path('', views.IndexClassView.as_view(), name="index"),
    path('<int:pk>/', views.FoodDetail.as_view(), name='detail'),
    path('item/', views.item, name='item'),
    path('add', views.CreateItem.as_view(), name='create_item'),
    path('update/<int:id>/', views.update_item, name='update_item'),
    path('delete/<int:id>/', views.delete_item, name="delete_item")
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from users import views as user_views
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as authentication_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('food/', include('food.urls')),
    path('register/', user_views.register, name='register'),
    path('login/', authentication_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', authentication_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('profile/', user_views.profilepage, name='profile'),
    
]

urlpatterns += [
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

food/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

class Item(models.Model):
    user_name = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    item_name = models.CharField(max_length=200)
    item_desc = models.CharField(max_length=200)
    item_price = models.IntegerField()
    item_image = models.CharField(max_length=500, default="https://toppng.com/uploads/preview/clipart-free-seaweed-clipart-draw-food-placeholder-11562968708qhzooxrjly.png")
    
    def __str__(self):
        return self.item_name

    def get_absolute_url(self):
        return reverse("food:detail", kwargs={"pk": self.pk})
    

users/models.py
from django.db import models
from django.contrib.auth.models import User

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='profilepic.jpg', upload_to='profile_pictures')
    location = models.CharField(max_length=100)
    
    def __str__(self):
        return self.user.username

food/forms.py
from django import forms
from .models import Item

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = [
            'item_name', 'item_desc', 'item_price', 'item_image',
        ]

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class RegisterForm(UserCreationForm):
    email = forms.EmailField()
    
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

food/views.py
from django.http import HttpResponse
from django.shortcuts import redirect, render
from .models import Item
from .forms import ItemForm
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView

def index(request):
    item_list = Item.objects.all()
    context = {
        'item_list': item_list,
    }
    return render(request, 'food/index.html', context)

class IndexClassView(ListView):
    model = Item
    template_name= 'food/index.html'
    context_object_name = 'item_list'
    
def item(request):
    return HttpResponse('This is an item view')

def detail(request, item_id):
    item = Item.objects.get(pk=item_id)
    
    context = {
        'item': item
    }
    
    return render(request, 'food/detail.html', context)

class FoodDetail(DetailView):
    model = Item
    template_name = 'food/detail.html'

def create_item(request):
    form = ItemForm(request.POST or None)
    
    if form.is_valid():
        form.save()
        return redirect('food:index')
    
    return render(request, 'food/item-form.html', {'form':form})

class CreateItem(CreateView):
    model = Item
    fields = ['item_name', 'item_desc', 'item_price', 'item_image']
    template_name = 'food/item-form.html'
    
    def form_valid(self, form):
        form.instance.user_name = self.request.user
        
        return super().form_valid(form)

def update_item(request, id):
    item = Item.objects.get(id=id)
    form = ItemForm(request.POST or None, instance=item)
    
    if form.is_valid():
        form.save()
        return redirect('food:index')
    
    return render(request, 'food/item-form.html', {'form':form, 'item':item})

def delete_item(request, id):
    item = Item.objects.get(id=id)
    
    if request.method == 'POST':
        item.delete()
        return redirect('food:index')
    
    return render(request, 'food/item-delete.html', {'item':item})

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import RegisterForm

def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Welcome {username}, your account is created.')
            return redirect('login')
    else:
        form = RegisterForm()
    return render(request, 'users/register.html', {'form':form})

@login_required
def profilepage(request):
    return render(request, 'users/profile.html')

food/templates/food/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'food/style.css' %}" >
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    <title>Food App</title>
</head>
<body>
    <nav class="navbar navbar-dark bg-dark">
        <a href="{% url 'food:index' %}" class="navbar-brand mx-2 py-3 ps-3">FoodApp</a>
        <div class="navbar-nav d-flex flex-row px-3">
            <a href="{% url 'food:create_item' %}" class="nav-item nav-link mx-2">Add Item</a>
            <a href="#" class="nav-item nav-link mx-2">Delete Item</a>
            <a href="#" class="nav-item nav-link mx-2">View Item</a>
            {% if user.is_authenticated  %}
            <a href="{% url 'logout' %}" class="nav-item nav-link mx-2 text-danger">Logout</a>
            <a href="{% url 'profile' %}" class="nav-item nav-link mx-2">Profile</a>
            {% else %}
            <a href="{% url 'login' %}" class="nav-item nav-link mx-2 text-primary">Login</a>
            {% endif %}
        </div>
    </nav>
    {% if messages  %}
        {% for message in messages %}
            <div class="alert alert-{{message.tags}}">
                {{message}}   
            </div>
            
        {% endfor %}
    {% endif %}
    {% block body %}
    {% endblock  %}
</body>
</html>

food/templates/food/detail.html
{% extends 'food/base.html' %}

{% block body %}
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <img src="{{ item.item_image }}" class="card" width="500" />
      </div>

      <div class="col-md-6">
        <h1>{{ object.item_name }}</h1>
        <h2>{{ object.item_desc }}</h2>
        <h3>$ {{ object.item_price }}.00</h3>
        <a href="{% url 'food:delete_item' item.id %}" class="btn btn-danger">Delete</a>
      </div>
    </div>
  </div>

  <br />
  <a href="/food/" class="btn btn-outline-primary">Back</a>
{% endblock %}

food/templates/food/index.html
{% extends 'food/base.html' %}
    
    {% block body %}
        {% for item in item_list %}
        <div class="row m-3">
            <div class="col-md-3 offset-md-2">
                <img class="card" width="300" height="200" src="{{item.item_image}}"/>
            </div>
            <div class="col-md-4">
                <h3>{{item.item_name}}</h3>
                <h5>{{item.item_desc}}</h5>
                <h6>${{item.item_price}}.00</h6>
                <h6>{{item.user_name}}</h6>
            </div>
            <div class="col-md-2">
                <a href="{% url 'food:detail' item.id %}" class="btn btn-success">Details</a>
            </div>
        </div>
        <hr>
        {% endfor %}
    {% endblock  %}

food/templates/food/item-delete.html
<form method="POST">
    {% csrf_token %}
    <h2>Are you sure you want to delete {{item.item_name}}?</h2>
    <button type="submit">Confirm</button>
</form>

food/templates/food/item-form.html
{% extends 'food/base.html' %}

{% block body %}
  <div class="container">
    <div class="row">
      <div class="col-md-4 offset-md-4">
        <div class="card">
          <div class="card-header text-white bg-info">
            <div class="card-title">Add Item</div>
          </div>
          <div class="card-body">
            <form method="POST">
              {% csrf_token %}
              {{form}}
              <button type="submit" class="btn btn-info text-white">ADD</button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

users/templates/users/login.html
{% extends 'food/base.html' %}

{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                <div class="card-header text-white bg-info">
                    <div class="card-title">Login</div>
                </div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="form-group my-2">
                                {{field.name}}
                                {{field}}
                            </div>
                        {% endfor %}
                        <button class="btn btn-info text-white" type="submit">Login</button>
                      </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

users/templates/users/logout.html
<h1>You have been logged out...</h1>

users/templates/users/profile.html
<h1>{{user.username}}</h1>
<img src="{{user.profile.image.url}}" alt="profile image" width="200">

users/templates/users/register.html
{% extends 'food/base.html' %}

{% block body %}
  <div class="container">
    <div class="row">
      <div class="col-md-4 offset-md-4">
        <div class="card">
          <div class="card-header text-white bg-info">
            <div class="card-title">Register</div>
          </div>
          <div class="card-body">
            <form method="POST" class="mt-4 ms-2">
              {% csrf_token %}
              {% for field in form %}
                <div class="form-group my-2">
                  {{field.name}}
                  <br>
                  {{field}}
                </div>
              {% endfor %}
              <br />
              <button type="submit" class="btn btn-info text-white">Signup</button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}